### ISSUE TITLE
F

### ISSUE THREAD

**Issue by Realminicao** [catalizcs/mirai#25]
![IMG_20201006_232706.jpg](https://user-images.githubusercontent.com/60745960/95230085-9452c380-082b-11eb-812b-75c92d9ed1bc.jpg)

**Comment by BadAimWeeb** [comment]
vãi lồn

**Comment by KDRXD** [comment]
Vê lờ

**Comment by catalizcs** [comment]
no u

**Comment by chinchinloli** [comment]
😳
