### ISSUE TITLE
Đổi ngôn ngữ 

### ISSUE THREAD

**Issue by lminh929** [catalizcs/mirai#26]
Làm sao để đổi ngôn ngữ Mirai BOT hả ô?

**Comment by meewmeew** [comment]
thay từng từ 1 =))

**Comment by lminh929** [comment]
> thay từng từ 1 =))

Realy?? :V

**Comment by lminh929** [comment]
Với tôi có thể xem danh sách người dùng bị ban ở đâu?

**Comment by catalizcs** [comment]
> Với tôi có thể xem danh sách người dùng bị ban ở đâu?

trong phần admin settings ông nhé

**Comment by catalizcs** [comment]
> Làm sao để đổi ngôn ngữ Mirai BOT hả ô?

còn phần này bọn tôi sẽ lên kế hoạch làm sau!

**Comment by BadAimWeeb** [comment]
that should be something right from the start, isn't it?

**Comment by catalizcs** [comment]
> that should be something right from the start, isn't it?

nah

**Comment by catalizcs** [comment]
bọn tôi đã có làm phần ngôn ngữ bên mirai-beta rồi nhé, ông có thể thử: https://github.com/catalizcs/mirai-beta

**Comment by catalizcs** [comment]
@lminh929

**Comment by lminh929** [comment]
Vào Th 3, 27 thg 10, 2020 lúc 11:50 Vũ Nguyễn Thành Tâm <
notifications@github.com> đã viết:
