### ISSUE TITLE
Api :3

### ISSUE THREAD

**Issue by KDRXD** [catalizcs/mirai#27]
Liệu có cái Api nào là tool tự cân bằng phương trình hóa học để add vào bot không :)))
Có thì con bot nó lại bodoi quá :)))

**Comment by catalizcs** [comment]
có thì có đấy nhưng mà 🤔

**Comment by meewmeew** [comment]
> có thì có đấy nhưng mà 🤔

có luôn à :v

**Comment by KDRXD** [comment]
> > có thì có đấy nhưng mà 🤔
> 
> có luôn à :v

Có chứ

**Comment by meewmeew** [comment]
> > > có thì có đấy nhưng mà 🤔
> > 
> > 
> > có luôn à :v
> 
> Có chứ

xịn :v

**Comment by KDRXD** [comment]
> > > > có thì có đấy nhưng mà 🤔
> > > 
> > > 
> > > có luôn à :v
> > 
> > 
> > Có chứ
> 
> xịn :v

:)))

**Comment by KDRXD** [comment]
> > > > > có thì có đấy nhưng mà 🤔
> > > > 
> > > > 
> > > > có luôn à :v
> > > 
> > > 
> > > Có chứ
> > 
> > 
> > xịn :v
> 
> :)))

Lên gg 

> > > > có thì có đấy nhưng mà 🤔
> > > 
> > > 
> > > có luôn à :v
> > 
> > 
> > Có chứ
> 
> xịn :v

Lên gg search Chemical Equation Balancer ra một đống

**Comment by meewmeew** [comment]
> > > > > > có thì có đấy nhưng mà 🤔
> > > > > 
> > > > > 
> > > > > có luôn à :v
> > > > 
> > > > 
> > > > Có chứ
> > > 
> > > 
> > > xịn :v
> > 
> > 
> > :)))
> 
> Lên gg
> 
> > > > > có thì có đấy nhưng mà 🤔
> > > > 
> > > > 
> > > > có luôn à :v
> > > 
> > > 
> > > Có chứ
> > 
> > 
> > xịn :v
> 
> Lên gg search Chemical Equation Balancer ra một đống

mình gà, có biết j âu

**Comment by catalizcs** [comment]
welp thực chất là bọn tôi cũng đã có làm sơ qua cân bằng rồi nhưng vẫn trong giai đoạn wip nên bọn tôi sẽ hoàn thiện trong tương lai, còn khi nào hoàn thiện thì issue này sẽ được ping tới pull request nhé : D

**Comment by KDRXD** [comment]
> welp thực chất là bọn tôi cũng đã có làm sơ qua cân bằng rồi nhưng vẫn trong giai đoạn wip nên bọn tôi sẽ hoàn thiện trong tương lai, còn khi nào hoàn thiện thì issue này sẽ được ping tới pull request nhé : D

Oh yê oh yê :Đ

**Comment by BadAimWeeb** [comment]
jsdom go brrrr

**Comment by catalizcs** [comment]
do late brrr
