### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by votientien888** [catalizcs/mirai#33]
Mong v2 sẽ có tính năng đếm tin nhắn cho các box( chỉ có admin box mới có thể reset bộ đếm cho box)
Tính năng thông báo tin nhắn gỡ. Không hiển thị liên kết khi gỡ hình ảnh. Và có thể nào bật lệnh thông báo tin nhắn gỡ của tất cả các box chỉ với 1 lệnh không

**Comment by catalizcs** [comment]
1/ v2 chắc chắn sẽ có việc thống kê tổng quan dành cho từng nhóm để các qtv nhóm có thể quản lý dễ dàng hơn => tất nhiên sẽ có việc reset
2/ v2 sẽ có bật tắt việc resend ảnh hoặc tệp đính kèm nào đó để đảm bảo an toàn, riêng tư của người dùng, tất nhiên chỉ có qtv là có thể bật, tắt để tránh việc các nhóm lợi dụng sơ hở đánh cắp thông tin 😉

**Comment by votientien888** [comment]
> 1/ v2 chắc chắn sẽ có việc thống kê tổng quan dành cho từng nhóm để các qtv nhóm có thể quản lý dễ dàng hơn => tất nhiên sẽ có việc reset
> 2/ v2 sẽ có bật tắt việc resend ảnh hoặc tệp đính kèm nào đó để đảm bảo an toàn, riêng tư của người dùng, tất nhiên chỉ có qtv là có thể bật, tắt để tránh việc các nhóm lợi dụng sơ hở đánh cắp thông tin 😉

Vậy bây giờ có cách nào để resend nó hiện liên kết ảnh k

**Comment by catalizcs** [comment]
"/ có lẽ là có nhưng phải tự code thêm

**Comment by votientien888** [comment]
> "/ có lẽ là có nhưng phải tự code thêm

Giúp e với

**Comment by catalizcs** [comment]
liên lạc minh qua https://fb.me/CatalizCS nhé
